/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;

import Controller.KnightController;
import Model.Knight;
import javax.swing.*;
import java.io.*;
import java.util.*;
import java.util.List;
import java.util.ArrayList;
import java.awt.GridLayout;
import javax.swing.ImageIcon;
import java.awt.Image;


public class KnightJanela extends javax.swing.JFrame {

    private KnightController controller = new KnightController();
    private List<Knight> knightsList = new ArrayList<>();
    private int currentIndex = 0;
    private JLabel backgroundLabel;
    /**
     * Creates new form Knight
     */
    public KnightJanela() {
        initComponents();
        carregarKnights(); // Carregar os knights ao iniciar a janela
        exibirKnight(); // Exibir o primeiro Knight
        setLocationRelativeTo(null);
        
        ImageIcon backgroundImage = new ImageIcon(getClass().getResource("/imagens/1.png"));
        Image img = backgroundImage.getImage().getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_SMOOTH);
        backgroundLabel = new JLabel(new ImageIcon(img));

        backgroundLabel.setBounds(0, 0, this.getWidth(), this.getHeight());

        // Usar layout nulo para posicionar o JLabel no fundo
        getLayeredPane().setLayout(null);
        getLayeredPane().add(backgroundLabel, new Integer(Integer.MIN_VALUE));

        // Deixar o painel principal transparente para o fundo aparecer
        ((JPanel) this.getContentPane()).setOpaque(false);

        // Ajustar tamanho e outras configurações da janela (se quiser)
        setSize(500, 500);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    private void carregarKnights() {
        try (BufferedReader reader = new BufferedReader(new FileReader("src/Personagens/knights.txt"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] dados = line.split(",");
                if (dados.length == 3) {
                    String nome = dados[0];
                    int level = Integer.parseInt(dados[1]);
                    int skill = Integer.parseInt(dados[2]);
                    knightsList.add(new Knight(nome, level, skill));
                }
            }
        } catch (IOException e) {
            System.out.println("Erro ao carregar os knights: " + e.getMessage());
        }
    }

    // Exibir o knight atual no JLabel
    private void exibirKnight() {
        if (!knightsList.isEmpty()) {
            Knight currentKnight = knightsList.get(currentIndex);
            jLabelKnightSalvos.setText("Nome: " + currentKnight.getNome()
                    + " | Level: " + currentKnight.getLevel()
                    + " | Skill: " + currentKnight.getSkill());
        } else {
            jLabelKnightSalvos.setText("Nenhum Knight salvo.");
        }
    }

    private void atualizarArquivo() {
        try (PrintWriter writer = new PrintWriter(new FileWriter("src/Personagens/knights.txt"))) {
            for (Knight knight : knightsList) {
                writer.println(knight.getNome() + "," + knight.getLevel() + "," + knight.getSkill());
            }
            System.out.println("Arquivo knights.txt atualizado com sucesso!");
        } catch (IOException e) {
            System.out.println("Erro ao atualizar o arquivo knights.txt: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButtonSalvarKnight = new javax.swing.JButton();
        jButtonExcluirKnight = new javax.swing.JButton();
        jButtonAlterarKnight = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomeKnight = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldLevelKnight = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneSkillKnight = new javax.swing.JTextPane();
        jLabelKnightSalvos = new javax.swing.JLabel();
        jButtonPassarKnight = new javax.swing.JButton();
        jButtonPesquisarKnight = new javax.swing.JButton();

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonSalvarKnight.setText("Salvar");
        jButtonSalvarKnight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalvarKnightMouseClicked(evt);
            }
        });
        jButtonSalvarKnight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarKnightActionPerformed(evt);
            }
        });

        jButtonExcluirKnight.setText("Excluir");
        jButtonExcluirKnight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonExcluirKnightMouseClicked(evt);
            }
        });

        jButtonAlterarKnight.setText("Alterar");
        jButtonAlterarKnight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAlterarKnightMouseClicked(evt);
            }
        });
        jButtonAlterarKnight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarKnightActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(51, 255, 51));
        jLabel1.setText("Nome");

        jTextFieldNomeKnight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeKnightActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(102, 255, 102));
        jLabel2.setText("Level");

        jLabel3.setForeground(new java.awt.Color(51, 255, 51));
        jLabel3.setText("Skill");

        jTextFieldLevelKnight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLevelKnightActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTextPaneSkillKnight);

        jLabelKnightSalvos.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabelKnightSalvos.setForeground(new java.awt.Color(51, 255, 51));

        jButtonPassarKnight.setText("Atualizar ou >>>");
        jButtonPassarKnight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPassarKnightMouseClicked(evt);
            }
        });
        jButtonPassarKnight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPassarKnightActionPerformed(evt);
            }
        });

        jButtonPesquisarKnight.setText("Pesquisar");
        jButtonPesquisarKnight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPesquisarKnightMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelKnightSalvos, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldNomeKnight, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                    .addComponent(jTextFieldLevelKnight)
                                    .addComponent(jScrollPane1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisarKnight)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonSalvarKnight)
                        .addGap(74, 74, 74)
                        .addComponent(jButtonExcluirKnight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPassarKnight)
                            .addComponent(jButtonAlterarKnight))
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNomeKnight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisarKnight))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldLevelKnight, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPassarKnight)
                    .addComponent(jLabelKnightSalvos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvarKnight)
                    .addComponent(jButtonExcluirKnight)
                    .addComponent(jButtonAlterarKnight))
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldLevelKnightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLevelKnightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLevelKnightActionPerformed

    private void jButtonAlterarKnightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarKnightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAlterarKnightActionPerformed

    private void jButtonSalvarKnightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalvarKnightMouseClicked
        // Pega os dados dos campos
        String nome = jTextFieldNomeKnight.getText();
        int level = Integer.parseInt(jTextFieldLevelKnight.getText());
        int skill = Integer.parseInt(jTextPaneSkillKnight.getText());

        // Cria o objeto Knight
        Knight knight = new Knight(nome, level, skill);

        // Salva usando o controller
        controller.salvar(knight);

        // Mensagem de sucesso
        JOptionPane.showMessageDialog(this, "Knight salvo com sucesso!");
        carregarKnights();
    }//GEN-LAST:event_jButtonSalvarKnightMouseClicked

    private void jButtonSalvarKnightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarKnightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalvarKnightActionPerformed

    private void jButtonPassarKnightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPassarKnightMouseClicked
        if (!knightsList.isEmpty()) {
            // Incrementar o índice para passar para o próximo knight
            currentIndex = (currentIndex + 1) % knightsList.size(); // Volta ao primeiro knight se ultrapassar o tamanho da lista
            exibirKnight(); // Atualiza a exibição do knight
        }
    }//GEN-LAST:event_jButtonPassarKnightMouseClicked

    private void jButtonPassarKnightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPassarKnightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPassarKnightActionPerformed

    private void jButtonExcluirKnightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExcluirKnightMouseClicked
        if (!knightsList.isEmpty()) {
            // Excluir o knight atual da lista
            knightsList.remove(currentIndex);

            // Se a lista não estiver vazia após a exclusão, ajusta o índice
            if (currentIndex >= knightsList.size()) {
                currentIndex = knightsList.size() - 1; // Se o índice for maior que o tamanho, vai para o último knight
            }

            // Atualiza a exibição
            exibirKnight();

            // Atualizar o arquivo knights.txt
            atualizarArquivo();
        } else {
            // Se não houver knights, exibe uma mensagem
            JOptionPane.showMessageDialog(this, "Não há knights para excluir.");
        }

    }//GEN-LAST:event_jButtonExcluirKnightMouseClicked

    private void jButtonAlterarKnightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAlterarKnightMouseClicked
        if (knightsList.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Não há knights para alterar.");
            return;
        }

        Knight currentKnight = knightsList.get(currentIndex);

        // Cria os campos e preenche com os dados atuais
        JTextField nomeField = new JTextField(currentKnight.getNome());
        JTextField levelField = new JTextField(String.valueOf(currentKnight.getLevel()));
        JTextField skillField = new JTextField(String.valueOf(currentKnight.getSkill()));

        JPanel panel = new JPanel(new GridLayout(0, 1));
        panel.add(new JLabel("Nome:"));
        panel.add(nomeField);
        panel.add(new JLabel("Level:"));
        panel.add(levelField);
        panel.add(new JLabel("Skill:"));
        panel.add(skillField);

        int resultado = JOptionPane.showConfirmDialog(this, panel, "Editar Knight",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (resultado == JOptionPane.OK_OPTION) {
            try {
                String novoNome = nomeField.getText().trim();
                int novoLevel = Integer.parseInt(levelField.getText().trim());
                int novoSkill = Integer.parseInt(skillField.getText().trim());

                // Atualiza os dados do knight
                currentKnight.setNome(novoNome);
                currentKnight.setLevel(novoLevel);
                currentKnight.setSkill(novoSkill);

                // Atualiza exibição e arquivo
                exibirKnight();
                atualizarArquivo();

                JOptionPane.showMessageDialog(this, "Knight alterado com sucesso!");
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Level e Skill devem ser números inteiros.");
            }
        }
    }//GEN-LAST:event_jButtonAlterarKnightMouseClicked

    private void jTextFieldNomeKnightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeKnightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeKnightActionPerformed

    private void jButtonPesquisarKnightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPesquisarKnightMouseClicked
        String nomePesquisa = jTextFieldNomeKnight.getText().trim();
        if (nomePesquisa.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, informe o nome para pesquisar.");
            return;
        }

        boolean encontrado = false;

        for (int i = 0; i < knightsList.size(); i++) {
            Knight k = knightsList.get(i);
            if (k.getNome().equalsIgnoreCase(nomePesquisa)) {
                // Atualiza campos com o Knight encontrado
                jTextFieldNomeKnight.setText(k.getNome());
                jTextFieldLevelKnight.setText(String.valueOf(k.getLevel()));
                jTextPaneSkillKnight.setText(String.valueOf(k.getSkill()));

                // Atualiza índice atual
                currentIndex = i;

                // Atualiza label
                exibirKnight();

                encontrado = true;
                break;
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "Knight com nome '" + nomePesquisa + "' não encontrado.");
        }

    }//GEN-LAST:event_jButtonPesquisarKnightMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KnightJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KnightJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KnightJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KnightJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KnightJanela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonAlterarKnight;
    private javax.swing.JButton jButtonExcluirKnight;
    private javax.swing.JButton jButtonPassarKnight;
    private javax.swing.JButton jButtonPesquisarKnight;
    private javax.swing.JButton jButtonSalvarKnight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelKnightSalvos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldLevelKnight;
    private javax.swing.JTextField jTextFieldNomeKnight;
    private javax.swing.JTextPane jTextPaneSkillKnight;
    // End of variables declaration//GEN-END:variables
}
