/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;

import Janelas.KnightJanela;
import Janelas.PaladinJanela;
import Janelas.SorcererJanela;
import Janelas.DruidJanela;
import Janelas.RankingJanela;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.awt.Image;
import javax.swing.*;
import java.awt.*;

public class Principal extends javax.swing.JFrame {

    private JLabel backgroundLabel;

    public Principal() {
        initComponents();  // inicializa seus botões, labels etc

        // Carrega e redimensiona a imagem do fundo
        ImageIcon backgroundImage = new ImageIcon(getClass().getResource("/imagens/NoPing48.jpg"));
        Image img = backgroundImage.getImage().getScaledInstance(500, 500, Image.SCALE_SMOOTH);
        ImageIcon resizedIcon = new ImageIcon(img);

        // Cria o JLabel do fundo
        backgroundLabel = new JLabel(resizedIcon);
        backgroundLabel.setBounds(0, 0, 500, 500);

        // Define layout nulo para posicionamento absoluto
        getLayeredPane().setLayout(null);

        // Adiciona o JLabel do fundo na camada mais baixa (BACKGROUND_LAYER)
        getLayeredPane().add(backgroundLabel, new Integer(Integer.MIN_VALUE));

        // Ajusta o tamanho da janela
        setSize(500, 500);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // Faz seu painel principal transparente para deixar ver o fundo
        ((JPanel)getContentPane()).setOpaque(false);
    }


    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonKnight = new javax.swing.JButton();
        jButtonSorcerer = new javax.swing.JButton();
        jButtonPaladin = new javax.swing.JButton();
        jButtonDruid = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonKnight.setText("Knight");
        jButtonKnight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonKnightMouseClicked(evt);
            }
        });
        jButtonKnight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKnightActionPerformed(evt);
            }
        });

        jButtonSorcerer.setText("Sorcerer");
        jButtonSorcerer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSorcererMouseClicked(evt);
            }
        });

        jButtonPaladin.setText("Paladin");
        jButtonPaladin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPaladinMouseClicked(evt);
            }
        });
        jButtonPaladin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPaladinActionPerformed(evt);
            }
        });

        jButtonDruid.setText("Druid");
        jButtonDruid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDruidMouseClicked(evt);
            }
        });
        jButtonDruid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDruidActionPerformed(evt);
            }
        });

        jButton1.setText("Ranking");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSorcerer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(jButtonKnight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(jButtonPaladin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(jButtonDruid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(294, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonKnight)
                .addGap(18, 18, 18)
                .addComponent(jButtonPaladin)
                .addGap(24, 24, 24)
                .addComponent(jButtonDruid)
                .addGap(18, 18, 18)
                .addComponent(jButtonSorcerer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPaladinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPaladinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPaladinActionPerformed

    private void jButtonDruidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDruidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDruidActionPerformed

    private void jButtonKnightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKnightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonKnightActionPerformed

    private void jButtonKnightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonKnightMouseClicked
        KnightJanela knightJanela = new KnightJanela();
        knightJanela.setVisible(true);
    }//GEN-LAST:event_jButtonKnightMouseClicked

    private void jButtonPaladinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPaladinMouseClicked
        PaladinJanela paladinJanela = new PaladinJanela();
        paladinJanela.setVisible(true);
    }//GEN-LAST:event_jButtonPaladinMouseClicked

    private void jButtonSorcererMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSorcererMouseClicked
        SorcererJanela sorcererJanela = new SorcererJanela();
        sorcererJanela.setVisible(true);
    }//GEN-LAST:event_jButtonSorcererMouseClicked

    private void jButtonDruidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDruidMouseClicked
        DruidJanela druidJanela = new DruidJanela();
        druidJanela.setVisible(true);
    }//GEN-LAST:event_jButtonDruidMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        RankingJanela rankingJanela = new RankingJanela();
        rankingJanela.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDruid;
    private javax.swing.JButton jButtonKnight;
    private javax.swing.JButton jButtonPaladin;
    private javax.swing.JButton jButtonSorcerer;
    // End of variables declaration//GEN-END:variables
}
