/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;

import Janelas.KnightJanela;
import Janelas.PaladinJanela;
import Janelas.SorcererJanela;
import Janelas.DruidJanela;

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setSize(180, 300);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonKnight = new javax.swing.JButton();
        jButtonSorcerer = new javax.swing.JButton();
        jButtonPaladin = new javax.swing.JButton();
        jButtonDruid = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonKnight.setText("Knight");
        jButtonKnight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonKnightMouseClicked(evt);
            }
        });
        jButtonKnight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKnightActionPerformed(evt);
            }
        });

        jButtonSorcerer.setText("Sorcerer");
        jButtonSorcerer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSorcererMouseClicked(evt);
            }
        });

        jButtonPaladin.setText("Paladin");
        jButtonPaladin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPaladinMouseClicked(evt);
            }
        });
        jButtonPaladin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPaladinActionPerformed(evt);
            }
        });

        jButtonDruid.setText("Druid");
        jButtonDruid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDruidMouseClicked(evt);
            }
        });
        jButtonDruid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDruidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSorcerer, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonKnight, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPaladin, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDruid, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButtonKnight)
                .addGap(18, 18, 18)
                .addComponent(jButtonPaladin)
                .addGap(24, 24, 24)
                .addComponent(jButtonDruid)
                .addGap(18, 18, 18)
                .addComponent(jButtonSorcerer)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPaladinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPaladinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPaladinActionPerformed

    private void jButtonDruidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDruidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDruidActionPerformed

    private void jButtonKnightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKnightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonKnightActionPerformed

    private void jButtonKnightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonKnightMouseClicked
        KnightJanela knightJanela = new KnightJanela();
        knightJanela.setVisible(true);

    }//GEN-LAST:event_jButtonKnightMouseClicked

    private void jButtonPaladinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPaladinMouseClicked
        PaladinJanela paladinJanela = new PaladinJanela();
        paladinJanela.setVisible(true);
    }//GEN-LAST:event_jButtonPaladinMouseClicked

    private void jButtonSorcererMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSorcererMouseClicked
        SorcererJanela sorcererJanela = new SorcererJanela();
        sorcererJanela.setVisible(true);
    }//GEN-LAST:event_jButtonSorcererMouseClicked

    private void jButtonDruidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDruidMouseClicked
        DruidJanela druidJanela = new DruidJanela();
        druidJanela.setVisible(true);
    }//GEN-LAST:event_jButtonDruidMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDruid;
    private javax.swing.JButton jButtonKnight;
    private javax.swing.JButton jButtonPaladin;
    private javax.swing.JButton jButtonSorcerer;
    // End of variables declaration//GEN-END:variables
}
