/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;

import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.WindowConstants;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import Ranking.GeradorRankings;


public class RankingJanela extends javax.swing.JFrame {

    /**
     * Creates new form RankingJanela
     */
    public RankingJanela() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButtonRKLVL = new javax.swing.JButton();
        jButtonLVLPDF = new javax.swing.JButton();
        jButtonRKML = new javax.swing.JButton();
        jButtonPDLML = new javax.swing.JButton();
        jButtonRKSKILL = new javax.swing.JButton();
        jButtonPDFSKILL = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonRKLVL.setText("RANKING LVL");
        jButtonRKLVL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRKLVLMouseClicked(evt);
            }
        });
        jButtonRKLVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRKLVLActionPerformed(evt);
            }
        });

        jButtonLVLPDF.setText("PDF RAKING");
        jButtonLVLPDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLVLPDFMouseClicked(evt);
            }
        });

        jButtonRKML.setText("RANKING ML");
        jButtonRKML.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRKMLMouseClicked(evt);
            }
        });

        jButtonPDLML.setText("PDF ML");
        jButtonPDLML.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPDLMLMouseClicked(evt);
            }
        });

        jButtonRKSKILL.setText("RAKING SKILL");
        jButtonRKSKILL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRKSKILLMouseClicked(evt);
            }
        });

        jButtonPDFSKILL.setText("PDF SKILL");
        jButtonPDFSKILL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPDFSKILLMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonRKLVL, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(jButtonLVLPDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRKML, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPDLML, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRKSKILL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPDFSKILL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jButtonRKLVL)
                .addGap(18, 18, 18)
                .addComponent(jButtonLVLPDF)
                .addGap(18, 18, 18)
                .addComponent(jButtonRKML)
                .addGap(18, 18, 18)
                .addComponent(jButtonPDLML)
                .addGap(18, 18, 18)
                .addComponent(jButtonRKSKILL)
                .addGap(18, 18, 18)
                .addComponent(jButtonPDFSKILL)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRKLVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRKLVLActionPerformed
        Ranking.GeradorRankings.visualizarRankingGeralNivel();
    }//GEN-LAST:event_jButtonRKLVLActionPerformed

    private void jButtonRKLVLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRKLVLMouseClicked

    }//GEN-LAST:event_jButtonRKLVLMouseClicked

    private void jButtonLVLPDFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLVLPDFMouseClicked
        Ranking.GeradorRankings.gerarPDFRankingGeralNivel();
    }//GEN-LAST:event_jButtonLVLPDFMouseClicked

    private void jButtonRKMLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRKMLMouseClicked
        Ranking.GeradorRankings.visualizarRankingGeralML();
    }//GEN-LAST:event_jButtonRKMLMouseClicked

    private void jButtonPDLMLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPDLMLMouseClicked
        Ranking.GeradorRankings.gerarPDFRankingGeralML();
    }//GEN-LAST:event_jButtonPDLMLMouseClicked

    private void jButtonRKSKILLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRKSKILLMouseClicked
        Ranking.GeradorRankings.visualizarRankingGeralSkill();
    }//GEN-LAST:event_jButtonRKSKILLMouseClicked

    private void jButtonPDFSKILLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPDFSKILLMouseClicked
        Ranking.GeradorRankings.gerarPDFRankingGeralSkill();
    }//GEN-LAST:event_jButtonPDFSKILLMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RankingJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RankingJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RankingJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RankingJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RankingJanela().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLVLPDF;
    private javax.swing.JButton jButtonPDFSKILL;
    private javax.swing.JButton jButtonPDLML;
    private javax.swing.JButton jButtonRKLVL;
    private javax.swing.JButton jButtonRKML;
    private javax.swing.JButton jButtonRKSKILL;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
