/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;

import Controller.SorcererController;
import Model.Sorcerer;
import javax.swing.*;
import java.io.*;
import java.util.*;
import java.util.List;
import java.util.ArrayList;
import java.awt.GridLayout;
import javax.swing.ImageIcon;
import java.awt.Image;

public class SorcererJanela extends javax.swing.JFrame {

    private SorcererController controller = new SorcererController();
    private List<Sorcerer> sorcerersList; // A lista será inicializada e preenchida pelo controller
    private int currentIndex = 0;
    private JLabel backgroundLabel;

    /**
     * Creates new form SorcererJanela
     */
    public SorcererJanela() {
        initComponents();
        carregarSorcerers(); // Carregar os Sorcerers ao iniciar a janela
        exibirSorcerer(); // Exibir o primeiro Sorcerer
        setLocationRelativeTo(null);

        ImageIcon backgroundImage = new ImageIcon(getClass().getResource("/imagens/3.png"));
        Image img = backgroundImage.getImage().getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_SMOOTH);
        backgroundLabel = new JLabel(new ImageIcon(img));

        backgroundLabel.setBounds(0, 0, this.getWidth(), this.getHeight());

        getLayeredPane().setLayout(null);
        getLayeredPane().add(backgroundLabel, new Integer(Integer.MIN_VALUE));

        ((JPanel) this.getContentPane()).setOpaque(false);

        setSize(500, 500);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    private void carregarSorcerers() {
        this.sorcerersList = controller.getTodosSorcerers(); // Obtém a lista do Controller

        if (sorcerersList.isEmpty()) {
            currentIndex = 0;
        } else if (currentIndex >= sorcerersList.size()) {
            currentIndex = sorcerersList.size() - 1;
        }
    }

    private void exibirSorcerer() {
        if (!sorcerersList.isEmpty() && currentIndex >= 0 && currentIndex < sorcerersList.size()) {
            Sorcerer currentSorcerer = sorcerersList.get(currentIndex);
            // Preencher os JTextFields e JTextPane com os dados do Sorcerer atual
            jTextFieldNomeSorcerer.setText(currentSorcerer.getNome()); // Assumindo jTextFieldNomeSorcerer
            jTextFieldLevelSorcerer.setText(String.valueOf(currentSorcerer.getLevel())); // Assumindo jTextFieldLevelSorcerer
            jTextPaneMagicLevelSorcerer.setText(String.valueOf(currentSorcerer.getMagicLevel())); // Assumindo jTextPaneMagicLevelSorcerer

            jLabelSorcererSalvos.setText("Nome: " + currentSorcerer.getNome()
                    + " | Level: " + currentSorcerer.getLevel()
                    + " | Magic Level: " + currentSorcerer.getMagicLevel()); // Alterado para Magic Level
        } else {
            // Limpa os campos se não houver Sorcerer para exibir
            jTextFieldNomeSorcerer.setText("");
            jTextFieldLevelSorcerer.setText("");
            jTextPaneMagicLevelSorcerer.setText("");
            jLabelSorcererSalvos.setText("Nenhum Sorcerer salvo.");
        }
    }

    // O método atualizarArquivo() não é mais necessário aqui.
    // private void atualizarArquivo() { ... }F
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButtonSalvarSorcerer = new javax.swing.JButton();
        jButtonExcluirSorcerer = new javax.swing.JButton();
        jButtonAlterarSorcerer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomeSorcerer = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldLevelSorcerer = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneMagicLevelSorcerer = new javax.swing.JTextPane();
        jLabelSorcererSalvos = new javax.swing.JLabel();
        jButtonPassarSorcerer = new javax.swing.JButton();
        jButtonPesquisarSorcerer = new javax.swing.JButton();

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonSalvarSorcerer.setText("Salvar");
        jButtonSalvarSorcerer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalvarSorcererMouseClicked(evt);
            }
        });
        jButtonSalvarSorcerer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarSorcererActionPerformed(evt);
            }
        });

        jButtonExcluirSorcerer.setText("Excluir");
        jButtonExcluirSorcerer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonExcluirSorcererMouseClicked(evt);
            }
        });

        jButtonAlterarSorcerer.setText("Alterar");
        jButtonAlterarSorcerer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAlterarSorcererMouseClicked(evt);
            }
        });
        jButtonAlterarSorcerer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarSorcererActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 51, 255));
        jLabel1.setText("Nome");

        jTextFieldNomeSorcerer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeSorcererActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 51, 255));
        jLabel2.setText("Level");

        jLabel3.setForeground(new java.awt.Color(255, 51, 255));
        jLabel3.setText("MagicLvl");

        jTextFieldLevelSorcerer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLevelSorcererActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTextPaneMagicLevelSorcerer);

        jLabelSorcererSalvos.setForeground(new java.awt.Color(255, 51, 255));

        jButtonPassarSorcerer.setText("Atualizar ou >>>");
        jButtonPassarSorcerer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPassarSorcererMouseClicked(evt);
            }
        });
        jButtonPassarSorcerer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPassarSorcererActionPerformed(evt);
            }
        });

        jButtonPesquisarSorcerer.setText("Pesquisar");
        jButtonPesquisarSorcerer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPesquisarSorcererMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelSorcererSalvos, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldNomeSorcerer, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                    .addComponent(jTextFieldLevelSorcerer)
                                    .addComponent(jScrollPane1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisarSorcerer)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonSalvarSorcerer)
                        .addGap(74, 74, 74)
                        .addComponent(jButtonExcluirSorcerer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAlterarSorcerer)
                            .addComponent(jButtonPassarSorcerer, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNomeSorcerer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisarSorcerer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldLevelSorcerer, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPassarSorcerer)
                    .addComponent(jLabelSorcererSalvos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvarSorcerer)
                    .addComponent(jButtonExcluirSorcerer)
                    .addComponent(jButtonAlterarSorcerer))
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldLevelSorcererActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLevelSorcererActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLevelSorcererActionPerformed

    private void jButtonAlterarSorcererActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarSorcererActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAlterarSorcererActionPerformed

    private void jButtonSalvarSorcererMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalvarSorcererMouseClicked
// Pega os dados dos campos e adiciona tratamento de erro
        String nome = jTextFieldNomeSorcerer.getText();

        int level = 0;
        try {
            level = Integer.parseInt(jTextFieldLevelSorcerer.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, insira um número válido para o Level.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
            return; // Sai do método se houver erro
        }

        int magicLevel = 0;
        try {
            magicLevel = Integer.parseInt(jTextPaneMagicLevelSorcerer.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, insira um número válido para o Magic Level.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
            return; // Sai do método se houver erro
        }

        // Cria o objeto Sorcerer
        Sorcerer sorcerer = new Sorcerer(nome, level, magicLevel);

        // Salva usando o controller
        controller.salvar(sorcerer);

        // Mensagem de sucesso
        JOptionPane.showMessageDialog(this, "Sorcerer salvo com sucesso!");

        // Recarrega a lista para refletir a adição e exibe o novo Sorcerer
        carregarSorcerers();
        currentIndex = sorcerersList.size() - 1; // Vai para o último adicionado
        exibirSorcerer();
    }//GEN-LAST:event_jButtonSalvarSorcererMouseClicked

    private void jButtonSalvarSorcererActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarSorcererActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalvarSorcererActionPerformed

    private void jButtonPassarSorcererMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPassarSorcererMouseClicked
        if (!sorcerersList.isEmpty()) {
            currentIndex = (currentIndex + 1) % sorcerersList.size();
            exibirSorcerer();
        }
    }//GEN-LAST:event_jButtonPassarSorcererMouseClicked

    private void jButtonPassarSorcererActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPassarSorcererActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPassarSorcererActionPerformed

    private void jButtonExcluirSorcererMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExcluirSorcererMouseClicked
        if (!sorcerersList.isEmpty() && currentIndex >= 0 && currentIndex < sorcerersList.size()) {
            String nomeParaExcluir = sorcerersList.get(currentIndex).getNome();
            int confirm = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir o Sorcerer " + nomeParaExcluir + "?", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                controller.excluir(nomeParaExcluir);
                JOptionPane.showMessageDialog(this, "Sorcerer " + nomeParaExcluir + " excluído com sucesso!");
                carregarSorcerers(); // Recarrega a lista para refletir a exclusão
                if (!sorcerersList.isEmpty()) {
                    if (currentIndex >= sorcerersList.size()) {
                        currentIndex = sorcerersList.size() - 1;
                    }
                    exibirSorcerer();
                } else {
                    exibirSorcerer(); // Exibe "Nenhum Sorcerer salvo."
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Nenhum Sorcerer para excluir.", "Erro", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonExcluirSorcererMouseClicked

    private void jButtonAlterarSorcererMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAlterarSorcererMouseClicked
        if (!sorcerersList.isEmpty() && currentIndex >= 0 && currentIndex < sorcerersList.size()) {
            String nomeOriginal = sorcerersList.get(currentIndex).getNome();

            // Pega os dados dos campos de texto da própria janela para alteração
            int level = 0;
            try {
                level = Integer.parseInt(jTextFieldLevelSorcerer.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Por favor, insira um número válido para o Level.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int magicLevel = 0;
            try {
                magicLevel = Integer.parseInt(jTextPaneMagicLevelSorcerer.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Por favor, insira um número válido para o Magic Level.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Chama o método alterar do controller
            controller.alterar(nomeOriginal, level, magicLevel);
            JOptionPane.showMessageDialog(this, "Dados do Sorcerer " + nomeOriginal + " alterados com sucesso!");

            // Recarrega a lista para refletir a alteração e exibe os dados atualizados
            carregarSorcerers();
            exibirSorcerer();
        } else {
            JOptionPane.showMessageDialog(this, "Nenhum Sorcerer selecionado para alterar.", "Erro", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAlterarSorcererMouseClicked

    private void jTextFieldNomeSorcererActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeSorcererActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeSorcererActionPerformed

    private void jButtonPesquisarSorcererMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPesquisarSorcererMouseClicked
        String nomePesquisa = jTextFieldNomeSorcerer.getText().trim();
        if (nomePesquisa.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, informe o nome para pesquisar.");
            return;
        }

        Sorcerer foundSorcerer = controller.buscarPorNome(nomePesquisa); // Usa o controller para buscar

        if (foundSorcerer != null) {
            // Atualiza campos com o Sorcerer encontrado
            jTextFieldNomeSorcerer.setText(foundSorcerer.getNome());
            jTextFieldLevelSorcerer.setText(String.valueOf(foundSorcerer.getLevel()));
            jTextPaneMagicLevelSorcerer.setText(String.valueOf(foundSorcerer.getMagicLevel()));

            // Atualiza o currentIndex para o Sorcerer encontrado
            carregarSorcerers(); // Garante que a lista local sorcerersList está atualizada antes de buscar o índice
            currentIndex = sorcerersList.indexOf(foundSorcerer);

            // Atualiza label
            exibirSorcerer();

            JOptionPane.showMessageDialog(this, "Sorcerer '" + nomePesquisa + "' encontrado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Sorcerer com nome '" + nomePesquisa + "' não encontrado.");
        }

    }//GEN-LAST:event_jButtonPesquisarSorcererMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SorcererJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SorcererJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SorcererJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SorcererJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SorcererJanela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonAlterarSorcerer;
    private javax.swing.JButton jButtonExcluirSorcerer;
    private javax.swing.JButton jButtonPassarSorcerer;
    private javax.swing.JButton jButtonPesquisarSorcerer;
    private javax.swing.JButton jButtonSalvarSorcerer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelSorcererSalvos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldLevelSorcerer;
    private javax.swing.JTextField jTextFieldNomeSorcerer;
    private javax.swing.JTextPane jTextPaneMagicLevelSorcerer;
    // End of variables declaration//GEN-END:variables
}
